<p style="text-align:center"> 
    <a href="https://www.linkedin.com/in/flavio-aguirre-12784a252/" target="_blank"> 
    <img src="../assets/logo.png" width="200" alt="Flavio Aguirre Logo"> 
    </a>
</p>

<h1 align="center"><font size="7"><strong>📉 ByeBye Predictor</strong></font></h1>
<br>
<hr>

## Telco Customer Churn – Baseline Model

**Date:** September 15, 2025<br>
**Subject:** Building baseline models for the Telco Customer Churn dataset.

This notebook aims to build a baseline model for the Telco Customer Churn dataset. The ModelBuilder class will be used, which automates model training, evaluation, and selection. The baseline will serve as a reference for subsequent comparisons with more advanced techniques (feature engineering, hyperparameter tuning, and integration with textual data).


##### ***Expected final result of Notebook 05***

* Establish a baseline performance benchmark for churn prediction.

* Generate key metrics and visualizations (confusion matrix, precision-recall curve, ROC curve) to diagnose model behavior.

* Provide a reference floor for future experimentation with feature engineering, hyperparameter optimization, and multimodal integration with textual data (Reddit comments).

<br>

### From Preprocessed Data to Baseline Models

Having a pristine and consistent dataset from the preprocessing stage, the next logical step is to establish a baseline benchmark. The baseline will not attempt to maximize performance through manual feature engineering or complex hyperparameter tuning. Instead, it provides a reference floor against which future improvements can be measured.

<br>

### Importing libraries and setup

In [1]:
from notebooks_setup import PROJECT_ROOT

from src.utils import get_logger
from src.data_loader import load_csv, preview_df
from src.eda import dataframe_overview
from src.model_builder import ModelBuilder
from src.model_evaluation import ModelEvaluatorConfig, ModelEvaluator 

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

2025-09-15 20:04:34,159 | src.utils | INFO | Added project root to sys.path: C:\Users\Pc\Desktop\github
2025-09-15 20:04:35,444 | src.model_builder | INFO | ModelBuilder Module initialized successfully!
2025-09-15 20:04:35,449 | src.model_evaluation | INFO | ModelEvaluator Module initialized successfully!

<br>

<hr>

### Loading the dataset and setup

In [2]:
logger = get_logger(__name__)

In [3]:
config = ModelEvaluatorConfig()

logger.info("Configuration applied:")
logger.info(f"Output directory: {config.out_dir}")
logger.info(f"Plotting style: {config.style}")

2025-09-15 20:04:38,447 | __main__ | INFO | Configuration applied:
2025-09-15 20:04:38,449 | __main__ | INFO | Output directory: ./reports/figures/baseline-model-telco/
2025-09-15 20:04:38,451 | __main__ | INFO | Plotting style: whitegrid

In [4]:
path_df_processed  = "data/processed/telco_churn_curated.csv"
df_processed = load_csv(path_df_processed)

logger.info(f"Shape: {df_processed.shape}")
preview_df(df_processed)

2025-09-15 20:04:39,743 | src.data_loader | INFO | Loaded CSV: data/processed/telco_churn_curated.csv | Shape: (7043, 30)

2025-09-15 20:04:39,745 | src.data_loader | INFO | Completed: load_csv
2025-09-15 20:04:39,747 | __main__ | INFO | Shape: (7043, 30)

,monthly_charges,tenure,total_charges,gender_male,partner_yes,dependents_yes,phone_service_yes,multiple_lines_no_phone_service,multiple_lines_yes,internet_service_fiber_optic,...,streaming_tv_yes,streaming_movies_no_internet_service,streaming_movies_yes,contract_one_year,contract_two_year,paperless_billing_yes,payment_method_credit_card_automatic,payment_method_electronic_check,payment_method_mailed_check,senior_citizen
0,-1.160323,-1.277445,-0.994242,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,-0.259629,0.066327,-0.173244,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,-0.362660,-1.236724,-0.959674,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,-0.746535,0.514251,-0.194766,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.197365,-1.236724,-0.940470,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0

<br>

### Target distribution

We remember that in our [Reports]("../reports/figures/eda/target_distribution.png") we already have our target variable distributed.
<div style="text-align:center">
    <img src="../reports/figures/eda/target_distribution.png" width="600" alt="target distribution">
</div>

We looked at the ratio of customers who churned versus those who stayed.
This is important because imbalance can affect model performance.

In [5]:
# Target load
path_target_processed = "data/processed/target_processed.csv"
target_processed = load_csv(path_target_processed)

2025-09-15 20:04:44,537 | src.data_loader | INFO | Loaded CSV: data/processed/target_processed.csv | Shape: (7043, 1)
2025-09-15 20:04:44,538 | src.data_loader | INFO | Completed: load_csv

<br>

### Definition of X and Y

In [6]:
X = df_processed
y = target_processed

logger.info("Set X and y defined correctly!")

2025-09-15 20:04:46,161 | __main__ | INFO | Set X and y defined correctly!

In [7]:
RANDOM_STATE = 42

logger.info("RANDOM_STATE set correctly")

2025-09-15 20:04:47,656 | __main__ | INFO | RANDOM_STATE set correctly

<br>

### Train/test split

In [8]:
logger.info("Separating data into training and test subsets...")
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, 
    stratify=y, 
    random_state=RANDOM_STATE
)

logger.info("Data correctly separated into training and test subsets!")
logger.info(f"Train size: {X_train.shape}, Test size: {X_test.shape}")

2025-09-15 20:04:49,694 | __main__ | INFO | Separating data into training and test subsets...
2025-09-15 20:04:49,723 | __main__ | INFO | Data correctly separated into training and test subsets!
2025-09-15 20:04:49,724 | __main__ | INFO | Train size: (5634, 30), Test size: (1409, 30)

<br>

### Construction of the models

We use our aforementioned pipeline (ModelBuilder) to build our models and evaluate them to obtain the one with the best statistics.

In [9]:
builder = ModelBuilder(task='classification', random_state=RANDOM_STATE)

The method uses cross-validation internally on X_train, y_train.

In [10]:
models_evaluation = builder.evaluate_models(X_train, y_train, cv=7)

2025-09-15 20:05:07,464 | src.model_builder | INFO | Cross-validating model: logistic_regression...
2025-09-15 20:05:09,897 | src.model_builder | INFO | Model logistic_regression evaluated successfully.
2025-09-15 20:05:09,898 | src.model_builder | INFO | Cross-validating model: decision_tree...
2025-09-15 20:05:11,532 | src.model_builder | INFO | Model decision_tree evaluated successfully.
2025-09-15 20:05:11,533 | src.model_builder | INFO | Cross-validating model: random_forest...
2025-09-15 20:05:12,420 | src.model_builder | INFO | Model random_forest evaluated successfully.
2025-09-15 20:05:12,421 | src.model_builder | INFO | Cross-validating model: xgboost...
2025-09-15 20:05:12,770 | src.model_builder | INFO | Model xgboost evaluated successfully.
2025-09-15 20:05:12,772 | src.data_loader | INFO | Completed: evaluate_models

In [11]:
evaluation_of_results_df = pd.DataFrame(models_evaluation)

logger.info("Results of all models applying the cross-validation method (7-fold average):")
evaluation_of_results_df

2025-09-15 20:05:19,657 | __main__ | INFO | Results of all models applying the cross-validation method (7-fold average):

                logistic_regression  decision_tree  random_forest   xgboost
fit_time                   0.037974       0.027133       0.581691  0.151896
score_time                 0.027576       0.020463       0.055056  0.033630
test_accuracy              0.751322       0.727900       0.786647  0.782745
test_precision             0.521235       0.488013       0.631312  0.609643
test_recall                0.804020       0.513091       0.476281  0.504378
test_f1                    0.632274       0.500039       0.542608  0.551700
test_roc_auc               0.845192       0.659852       0.824587  0.823869

<br>

### Construction of the baseline

#### Selecting Best Model

In [12]:
# We select the best model based on F1-score
builder.select_best_model(metric='test_f1')
best_model_name = builder.best_model_name_
logger.info(f"The best model according to F1-score is: '{best_model_name}'")

2025-09-15 20:05:34,426 | src.model_builder | INFO | Best model selected: logistic_regression with test_f1: 0.6323
2025-09-15 20:05:34,428 | src.data_loader | INFO | Completed: select_best_model
2025-09-15 20:05:34,430 | __main__ | INFO | The best model according to F1-score is: 'logistic_regression'

#### Train that specific model on the full training set

In [13]:
final_model = builder.train_final_model(best_model_name, X_train, y_train)

logger.info(f"Final model '{best_model_name}' trained with {X_train.shape[0]} samples.")

2025-09-15 20:05:39,569 | src.model_builder | INFO | Training final model: logistic_regression...
c:\Users\Pc\Desktop\github\byebye_predictor\.venv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
2025-09-15 20:05:39,606 | src.model_builder | INFO | Model logistic_regression trained successfully.
2025-09-15 20:05:39,608 | src.data_loader | INFO | Completed: train_final_model
2025-09-15 20:05:39,609 | __main__ | INFO | Final model 'logistic_regression' trained with 5634 samples.

<br>

### Final evaluation with the winning model on the test set

Now we use our dedicated module (ModelEvaluator) to analyze this model.

In [14]:
evaluator = ModelEvaluator(task="classification", save_dir=config.out_dir)

In [15]:
y_pred = final_model.predict(X_test)

#### Metrics

**We obtain that:**

In [23]:
metrics = evaluator.evaluate(final_model, X_test, y_test, run_name="baseline_no_features")

evaluator.compare_runs().T

2025-09-15 20:10:02,531 | src.data_loader | INFO | Completed: evaluate

           baseline_no_features
accuracy               0.738822
precision              0.796882
recall                 0.738822
f1                     0.752588

#### Classification report

In [17]:
logger.info(f"Final classification report for '{best_model_name}':")
print(classification_report(y_test, y_pred))

2025-09-15 20:05:54,848 | __main__ | INFO | Final classification report for 'logistic_regression':

              precision    recall  f1-score   support

           0       0.90      0.72      0.80      1035
           1       0.51      0.78      0.61       374

    accuracy                           0.74      1409
   macro avg       0.70      0.75      0.71      1409
weighted avg       0.80      0.74      0.75      1409

This report indicates that the model's performance is balanced, although with marked differences between the prediction of customers who do not churn (Class 0) and those who do churn (Class 1):

**Class 0 (No Churn):**

* Accuracy (0.90) → When the model predicts that a customer will not churn, it is correct in 90% of cases.

* Recall (0.72) → It correctly identifies 72% of customers who do not churn.

* F1-score (0.80) → Good balance between precision and recall.

**Class 1 (Churn):**

* Accuracy (0.51) → Of all customers predicted as churn, only 51% actually churn (high level of false positives).

* Recall (0.78) → The model detects 78% of customers who actually churn, which is positive in terms of churn reduction.

* F1-score (0.61) → Moderate performance, limited by low precision.

**Overall metrics:**

* Accuracy (0.74) → 74% of predictions are correct.

* Macro Avg (0.71) → The average performance between both classes is balanced, although lower in the churn class.

* Weighted Avg (0.75) → Reflects the actual weight of each class in the dataset, confirming that the model is stronger at predicting "No Churn."

#### Confusion Matrix

In [18]:
confusion_matrix = evaluator.plot_confusion_matrix(
    y_test, 
    y_pred, 
    labels=["No Churn", "Churn"],
    title=f"Best baseline confusion matrix ({best_model_name})",
    filename=f"confusion_matrix_best_baseline_{best_model_name}.png"
)

2025-09-15 20:06:02,855 | src.model_evaluation | INFO | Plot saved to ./reports/figures/baseline-model-telco/confusion_matrix_best_baseline_logistic_regression.png

#### ROC Curve

In [19]:
roc_curve =evaluator.plot_roc_curve(
    final_model, 
    X_test, 
    y_test,
    title=f"Best baseline ROC Curve ({best_model_name})",
    filename=f"roc_curve_best_baseline_{best_model_name}.png"
)

2025-09-15 20:06:06,151 | src.model_evaluation | INFO | Plot saved to ./reports/figures/baseline-model-telco/roc_curve_best_baseline_logistic_regression.png

#### Precision-Recall Curve

In [20]:
precision_recall = evaluator.plot_precision_recall(
    final_model, 
    X_test, 
    y_test,
    title=f"Best baseline Precision-Recall Curve ({best_model_name})",
    filename=f"precision_recall_curve_best_baseline_{best_model_name}.png"
)

2025-09-15 20:06:10,008 | src.model_evaluation | INFO | Plot saved to ./reports/figures/baseline-model-telco/precision_recall_curve_best_baseline_logistic_regression.png

<br>

### Final results of this laboratory

##### Classification Report

We can deduce that the ``logistic regression`` baseline achieves solid initial performance (AUC 0.84 and accuracy 74%), with clear strength in identifying customers who don't churn and high recall for those who do. However, the low churn accuracy implies false positives: the model overestimates the number of customers who would churn.

##### Confusion Matrix

<div style="text-align:center">
    <img src="../reports/figures/baseline-model-telco/confusion_matrix_best_baseline_logistic_regression.png" width="600" alt="Confusion Matrix baseline">
</div>

The model is quite good at detecting customers who are staying (high TN = ["No churn","No churn"]).

It has a relatively low FN (["No churn","Churn"]) (81), which is positive because in churn, the most expensive thing is not detecting a customer who actually leaves.

However, there is a significant number of FPs (False Positive ["churn","no churn"] = 287) → the model "over-triggers alarms" by predicting that some customers will leave when in reality they won't.

This means that if a company decides to invest in customer retention based on this model, it will waste efforts on customers who weren't going to leave.

##### ROC Curve

<div style="text-align:center">
    <img src="../reports/figures/baseline-model-telco/roc_curve_best_baseline_logistic_regression.png" width="600" alt="Confusion Matrix baseline">
</div>

With an AUC of 0.84, the model has an excellent ability to distinguish between churning and retaining customers.

This means that, given one customer who churns and one who doesn't, there is an 84% probability that the model will assign a higher probability of churn to the churner.

In the business world, this indicates that logistic regression is already a solid foundation, although there is still room for improvement with feature engineering or more complex models.

##### Precision-Recall Curve

<div style="text-align:center">
    <img src="../reports/figures/baseline-model-telco/precision_recall_curve_best_baseline_logistic_regression.png" width="600" alt="Confusion Matrix baseline">
</div>

In the graph, the initial accuracy is quite good (~0.75-0.8 on average), but it begins to drop sharply after ~0.5 recall.
This implies that the model cannot reliably detect all churners, but it can be useful in scenarios where you want to prioritize customers with a high probability of churning.

<br>

### Saving results

Well, since we already have our preprocessing pipeline obtained in the previous module and our already trained model, we could combine everything to have a basic churn tool and ensure that if we receive a raw dataset in production, we can apply pipeline.predict() directly without having to manually repeat the preprocessing.

But since this is a personal project, we'll keep it modular, that is, we'll keep them separate as they are. We only save the trained model.

In [36]:
builder.save_model(best_model_name, f"models/baseline/{best_model_name}_v1_2025-09-15.joblib")

2025-09-15 19:47:50,164 | src.model_builder | INFO | Model logistic_regression saved to models/baseline/logistic_regression_v1_2025-09-15.joblib
2025-09-15 19:47:50,166 | src.data_loader | INFO | Completed: save_model

<br>

### Conclusion of this laboratory

* The baseline results confirm that the dataset contains sufficient predictive signal, but also highlight areas for improvement: reducing false positives and improving recall without compromising precision. These insights will guide the next phase of the project.

* The logistic regression baseline delivered a solid performance, achieving an accuracy of 74% and an AUC of 0.84.

* The precision-recall trade-off confirmed the model’s ability to capture a high proportion of churners (recall = 0.78), albeit with moderate precision (0.51), indicating potential over-allocation of retention resources.

* The classification report highlighted that performance is unbalanced between classes: the model performs better on the majority class (No Churn) than on the minority class (Churn).

* The separation between preprocessing pipeline and model training allows for modular experimentation but will require careful synchronization in production environments.

<br>

#### Next Steps


Based on these results, the following actions are recommended:

--->1. **Feature Engineering:**              Create new features and interactions to improve model performance.

2. **Hyperparameter Tuning:**  
   Optimize model parameters for better accuracy and recall.
3. **Integration of Textual Data:**  
   Incorporate customer comments for sentiment analysis and further enrichment of predictions.

This concludes the baseline modeling phase, leaving us with a reproducible, interpretable, and benchmarked model against which future enhancements will be measured.

<br>

<hr>

### Author

<a href="https://www.linkedin.com/in/flavio-aguirre-12784a252/">**Flavio Aguirre**</a>
<br>
<a href="https://coursera.org/share/e27ae5af81b56f99a2aa85289b7cdd04">***Data Scientist***</a>